CREATE TABLE EMPLOYEE(
	EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    SALARY DOUBLE,
    DEPARTMENT_ID INT,
    
    foreign key (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
    
    );
    
INSERT INTO EMPLOYEE(EMPLOYEE_ID, FIRST_NAME, LAST_NAME,SALARY, DEPARTMENT_ID) VALUES (1, "ASRAFUL", "MOLLA",2000, 101), (2, "RASED", "HASAN",3000, 102),(3, "RAJIA", "SULTANA",5000, 101); 

CREATE TABLE DEPARTMENT(
	DEPARTMENT_ID INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(50),
    LOCATION VARCHAR(50)
    );

INSERT INTO DEPARTMENT(DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION) VALUES (101, "CSE", "DHAKA"), (102, "EEE", "CUMILLA"); 

CREATE TABLE PROJECT(
	PROJECT_ID INT PRIMARY KEY,
    PROJECT_NAME VARCHAR(50),
    BUDGET INT,
    DEPARTMENT_ID INT,
    
    foreign key (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
    );


INSERT INTO PROJECT(PROJECT_ID, PROJECT_NAME, BUDGET, DEPARTMENT_ID) VALUES (201, "MLS", 1000, 101), (202, "PMS", 2000, 102);

-- 1 
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEE
WHERE FIRST_NAME LIKE "%J%";


-- 2
SELECT DEPARTMENT_NAME
FROM DEPARTMENT
WHERE LOCATION="DHAKA";

-- 3
SELECT PROJECT_NAME, BUDGET
FROM PROJECT
ORDER BY BUDGET DESC;

-- 4
SELECT FIRST_NAME
FROM EMPLOYEE
WHERE SALARY>75000 AND DEPARTMENT_ID !=3;

-- 5

SELECT SALARY, FIRST_NAME
FROM EMPLOYEE
WHERE SALARY=(
SELECT MAX(SALARY)
FROM EMPLOYEE
WHERE SALARY< (SELECT MAX(SALARY)
		FROM EMPLOYEE));

