
CREATE TABLE STUDENT(
	ROLL INT PRIMARY KEY,
    NAME VARCHAR(50),
    DEPT VARCHAR (10)
);

INSERT INTO STUDENT(ROLL, NAME, DEPT) VALUES (1, 'ASRAFUL MOLLA', 'CSE'); 
INSERT INTO STUDENT(ROLL, NAME, DEPT) VALUES (1, 'ASRAFUL MOLLA', 'CSE'); -- ERROR FIND OUT

SELECT *
FROM STUDENT;