-- CREATE DATABASE 

CREATE DATABASE LAB2;
-- DATABASE USE -- 
USE LAB2;
-- DELETE TABLE --
DROP DATABASE LAB2;
-- CREATE TABLE --
CREATE TABLE ST_INFO(
	ROLL INT, 
    NAME VARCHAR (50),
    DEPT VARCHAR (10)
);
-- INSERT SINGLE ROW -- 
INSERT INTO ST_INFO (ROLL, NAME, DEPT) VALUES (1, 'MD. ASRAFUL MOLLA', 'CSE');
INSERT INTO ST_INFO VALUES (2, 'RASHEDUZZAMAN', 'CSE');

-- INSERT MULTIPLE ROW -- 
INSERT INTO ST_INFO VALUES (3, 'RASHEDUZZAMAN', 'CSE'),(4, 'RASHEDUZZAMAN', 'CSE'), (5, 'RASHEDUZZAMAN', 'CSE') ;

-- SELECT QUERY -- 
SELECT * FROM ST_INFO;