CREATE TABLE EMPLOYEE(
EMP_ID INT PRIMARY KEY,
EMP_NAME VARCHAR(50),
SALARY DOUBLE
);

insert INTO EMPLOYEE(EMP_ID, EMP_NAME, SALARY) VALUES (1, 'A', 1000), (2, 'B', 3000),(3, 'C', 5000);

CREATE TABLE DEPARTMENT(
DEPT_ID INT PRIMARY KEY,
DEPT_NAME VARCHAR(50),
EMP_ID INT,
FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);

INSERT INTO DEPARTMENT(DEPT_ID, DEPT_NAME, EMP_ID) VALUES (101, 'CSE', 2), (102, 'EEE', 1), (103, 'BBA', 3);

CREATE TABLE EMP_DPT AS
SELECT EMPLOYEE.EMP_ID,EMPLOYEE.EMP_NAME,EMPLOYEE.SALARY,DEPARTMENT.DEPT_NAME
FROM EMPLOYEE
JOIN DEPARTMENT ON EMPLOYEE.EMP_ID=DEPARTMENT.EMP_ID;

SELECT *
FROM EMP_DPT;